### ISSUE TITLE
The number of rows in X must match the length of CLUST

### ISSUE THREAD

**Issue by ugultopu** [yooceii/AIBird#2]
# Steps to Reproduce
1. Clone the repository.
2. Run `python baseline.py` after cloning in the repository.

The program is exiting with the following error:

```
Error using silhouette (line 90)
The number of rows in X must match the length of CLUST.

Error in calculate_k (line 9)
    sil=silhouette(data,index);

Traceback (most recent call last):
  File "baseline.py", line 1235, in <module>
    structures = generate(m_height)
  File "baseline.py", line 398, in generate
    temp_leaf = prune(temp_leaf, step)
  File "baseline.py", line 473, in prune
    eng.calculate_k(nargout=0)
  File "/usr/local/lib/python3.6/site-packages/matlab/engine/matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "/usr/local/lib/python3.6/site-packages/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/usr/local/lib/python3.6/site-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: 
  File /Applications/MATLAB_R2018a.app/toolbox/stats/stats/silhouette.m, line 90, in silhouette

  File AIBird/calculate_k.m, line 9, in calculate_k
The number of rows in X must match the length of CLUST.
```

**Comment by yooceii** [comment]
I assume the problem is that the csv file name in Structure_prune is export_step_1.csv which is a test file instead of  export.csv. Please change the file name to export.csv to see if the problem still happens.

**Comment by ugultopu** [comment]
`export_step_1.csv` is a generated file, not a source file. So, there needs to be a change in the code in that case, right?

**Comment by yooceii** [comment]
Yes, just change the  export_step_1.csv to export.csv as the export.csv
file is a bunch of vectors and Structure_prune uses this file to clustering.
